### ISSUE TITLE
shell script won't work on Windows OS.

### ISSUE THREAD

**Issue by neallee2012** [hornpolish/docker.sas.awb#1]
When using Docker for Windows, it will fail while RUN /tmp/install_sas as shell script won't work on Windows OS.

**Comment by neallee2012** [comment]
I try to workaround it by 

1. comment RUN /tmp/install_sas
1. move the content of install_sas into Dockerfile as below
```
RUN set -x
RUN mkdir -p /etc/pki/sas/private
RUN cd /tmp/saspb; \
    wget -q -O sasorch.tgz https://support.sas.com/installation/viya/sas-orchestration-cli/lax/sas-orchestration.tgz; \
    tar xvfz sasorch.tgz; \
    ./sas-orchestration build --input SAS_Viya_deployment_data.zip; \
    tar xvfz SAS_Viya_playbook.tgz; \
    cd sas_viya_playbook; \
    sed -i "s/yum /yum -y /g" customized_deployment_script.sh; \
    ./customized_deployment_script.sh; \
    yum -y clean all; \
    cd /tmp; \
    rm -rf /tmp/saspb; \
    sed -i "s/\${ADMIN_USER}/cas/g" /opt/sas/viya/config/etc/cas/default/perms.xml; \
    cp /opt/sas/viya/home/SASFoundation/utilities/bin/sas-cascontroller.init /etc/rc.d/init.d/sas-viya-cascontroller-default; \
    chown sas:sas /etc/rc.d/init.d/sas-viya-cascontroller-default; \
    /sbin/chkconfig --add /etc/rc.d/init.d/sas-viya-cascontroller-default
```

**Comment by hornpolish** [comment]
Hi @neallee2012;  People have observed that you need to remove the /sys/fs/cgroup line form docker-compose.yml to run with "docker-compose up" on windows.  I'm away from my desktop that has windows, so i'll check on that later.  Are you trying to install into a windows container perhaps? i'm not familiar much with docker on windows options.

**Comment by neallee2012** [comment]
Hello @hornpolish, Yes, I am using Docker on Windows, it let people can use Linux container on Windows.
I got cgroup error before, I workaround this issue by adding a Windows env variable below.

$Env:COMPOSE_CONVERT_WINDOWS_PATHS=1

reference: https://github.com/docker/for-win/issues/1889

**Comment by hornpolish** [comment]
when i cloned the repo directly to my windows box, git changed the linendings to CRLF;  bash shell does not appreciate that.   what worked for me to build the image was:

git config --global core.eol lf 
git config --global core.autocrlf false
git clone https://github.com/hornpolish/docker.sas.awb.git   

now my cloned repo has "only" LF line-endings

i dont know how you cloned yours; does it have a way to say "preserve the repo line-endings"

paul

**Comment by neallee2012** [comment]
Hi Paul,

I think you can try to use .gitattributes<http://git-scm.com/docs/gitattributes> to prevent the file from being converted on windows.

Reference:
https://stackoverflow.com/questions/27810758/how-to-replace-crlf-with-lf-in-a-single-file

從我的 iPhone 傳送

Paul Kent <notifications@github.com<mailto:notifications@github.com>> 於 2018年7月3日 下午9:54 寫道：


EXTERNAL

when i cloned the repo directly to my windows box, git changed the linendings to CRLF; bash shell does not appreciate that. what worked for me to build the image was:

git config --global core.eol lf
git config --global core.autocrlf false
git clone https://github.com/hornpolish/docker.sas.awb.git

now my cloned repo has "only" LF line-endings

i dont know how you cloned yours; does it have a way to say "preserve the repo line-endings"

paul

**Comment by hornpolish** [comment]
Thanks for the tip!  I added a .gitattributes file to specify LF for all files in this repo
